### ISSUE TITLE
Output runtime versions

### ISSUE THREAD

**Issue by martincostello** [martincostello/update-dotnet-sdk#1301]
Versions of the .NET SDK are also associated with specific versions of the .NET runtime and ASP.NET Core.

To aid consumers with subsequent tasks, especially for non-stable builds (like previews or nightly builds), the action should output the runtime and ASP.NET Core version associated with the SDK.

### Stable

```yaml
sdk-version: '9.0.203'
runtime-version: '9.0.4'
aspnetcore-runtime-version: '9.0.4'
windowsdesktop-version: '9.0.4'
```

### Preview

```yaml
sdk-version: '10.0.100-preview.3.25201.16'
runtime-version: '10.0.0-preview.3.25171.5'
aspnetcore-runtime-version: '10.0.0-preview.3.25172.1'
windowsdesktop-version: '10.0.0-preview.3.25174.1'
```

### Daily

```yaml
sdk-version: '10.0.100-preview.4.25214.32'
runtime-version: '10.0.0-preview.4.25211.19'
aspnetcore-runtime-version: '10.0.0-preview.4.25212.2'
windowsdesktop-version: '10.0.0-preview.4.25211.2'
```
