### ISSUE TITLE
Target other repositories

### ISSUE THREAD

**Issue by martincostello** [martincostello/update-dotnet-sdk#528]
## Is your feature request related to a problem?

The action currently assumes that the .NET SDK updates are going to happen in the same repository in which the workflow is running. This precludes running a single workflow in one repository targeting one or more repositories somewhere else (e.g. running updates for all the repositories in an organisation).

## Describe the solution you'd like

Allow the repository to be overridden via a parameter. For example:

```yaml
name: update-dotnet-sdk

on:
  schedule:
    - cron:  '00 20 * * TUE'
  workflow_dispatch:

jobs:
  update-dotnet-sdk:
    name: Update .NET SDK
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        repository: my-org/my-repo
        token: ${{ secrets.MY_GITHUB_API_TOKEN }}
    - uses: martincostello/update-dotnet-sdk@v2
      with:
        repo: my-org/my-repo
        repo-token: ${{ secrets.MY_GITHUB_API_TOKEN }}
```

## Describe alternatives you've considered

None.

## Additional context

Adding support for this would allow for update workflows to be moved out of individual repositories and instead run centrally in another repository.
