### ISSUE TITLE
Only generate SDK update pull requests when there are security fixes

### ISSUE THREAD

**Issue by martincostello** [martincostello/update-dotnet-sdk#691]
## Is your feature request related to a problem?

Some users have a risk appetite that means they only update SDK/runtime/NuGet/etc versions when there is a security fix. Otherwise they prefer stability and to not update to versions that only contain non-security-related changes.

## Describe the solution you'd like

An opt-in setting to only create a pull request to update the .NET SDK when the release includes security fixes.

For example:

```yml
- uses: martincostello/update-dotnet-sdk@v3
  with:
    security-fixes-only: true
    repo-token: ${{ secrets.GITHUB_TOKEN }}
```

Worked example:

1. A repo uses version `x.0.100` of the .NET SDK
2. Version `x.0.101` of the .NET SDK is released which does not contain any security fixes.
3. No pull request to update the .NET SDK is opened.
4. Version `x.0.102` of the .NET SDK is released which contains one or more security fixes.
5. A pull request to update the .NET SDK from `x.0.100` to `x.0.102` is opened.

## Describe alternatives you've considered

None.

## Additional context

Suggested in [this YouTube stream](https://www.youtube.com/watch?v=pOeT1otTi4M&t=173s).
